
research_agent:
  temperature: 0.7
  max_tokens: 1000

food_agent:
  temperature: 0.7
  max_tokens: 1000

culture_agent:
  temperature: 0.7
  max_tokens: 1000

travel_agent:
  temperature: 0.7
  max_tokens: 1000

edit_agent:
  temperature: 0.7
  max_tokens: 1000
